[project]
name = "ssid-ivr-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cityseg",
]

[tool.uv.sources]
cityseg = { git = "https://github.com/MitchellAcoustics/cityseg" }
